version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_secret
      - MYSQL_DATABASE=jccar
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared-network
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files:/data_backup/data

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: /bin/sh -c "nginx -g 'deamon off;'"
    depends_on:
      api-prod:
        condition: service_healthy
      app-prod:
        condition: service_started
    networks:
      - shared-network

  api-prod:
    container_name: server_api_prod
    image: server-api-prod:1.0.0
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    # wait for mysqldb to be ready
    command: sh -c './bin/wait-for -t 0 mysqldb:3306 -- yarn run start:prod'
    depends_on:
      - mysqldb
    networks:
      - shared-network
    ports:
      - 9000:9000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', 'http://api-prod:9000']
      interval: 5s
      timeout: 3s
      retries: 6

  app-prod:
    container_name: jc_rental_prod
    image: jc-rental-prod:1.0.0
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    command: yarn run start:prod
    ports:
      - 3000:3000
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:

volumes:
  db-config:
  db-data:
